### PR TITLE
Remove unnecessary import of RLock

### PR DESCRIPTION
**Pull request by arjitarora26**

### CODE REVIEW

**Comment by classner** [comment]
Hi @arjitarora26 ,

Thanks for suggesting this change! The import, however, is intentional to populate the namespace of the `shared` module: it should contain all kinds of tools and structures for shared tooling support, and one of them is the rlock. Let me know if you have questions about this!

All the best,
Christoph

**Comment by arjitarora26** [comment]
Hi @classner,
Thanks for the reply. Just to confirm what you mentioned above.
Do you mean it is there to make `shared.rlock` available to the user?

Thanks,
Arjit

**Comment by classner** [comment]
Exactly!

**Comment by arjitarora26** [comment]
Thanks, got it!

**Pull request closed without merging**
